language: php

services:
  - mysql

php:
  - '7.1'
  - '7.2'

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test

script:
  - composer install
  - vendor/bin/simple-phpunit
