<?php
/**
 * File for ContactRepository
 *
 * PHP version 7.1
 * 
 * @category Contact
 * @package  ContactBundle\Repository
 * @author   Yoann Fleury <yoann.fleury@yahoo.com>
 * @license  MIT License
 * @link     /contacts
 */

namespace ContactBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * @category Contact
 * @package  ContactBundle\Repository
 * @author   Yoann Fleury <yoann.fleury@yahoo.com>
 * @license  MIT License
 * @link     /contacts
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{

}
