gesdinet_jwt_refresh_token:
    path:     /login/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

api_login_check:
    path: /login

contact:
    resource: "@ContactBundle/Controller/"
    type:     annotation
    prefix:   /

app.swagger:
    path: /doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
