# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        ContactBundle\Entity\User:
            algorithm: bcrypt

    providers:
        user_provider:
            entity:
                class: ContactBundle\Entity\User

    firewalls:
        doc:
            pattern: ^/doc
            stateless: true
            anonymous: true

        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: user_provider
            json_login:
                check_path:               /login
                username_path:            username
                password_path:            password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/(?!users|_profiler)
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/doc,     roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,        roles: IS_AUTHENTICATED_FULLY       }
