services:
    kernel.listener.exception:
        class: ContactBundle\Listener\ExceptionListener
        arguments: ["@logger", "@jms_serializer"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    contact.service.contact:
        class: ContactBundle\Service\ContactService
        arguments: ["@logger", "@doctrine.orm.entity_manager"]
    contact.service.phone:
        class: ContactBundle\Service\PhoneService
        arguments: ["@logger", "@doctrine.orm.entity_manager"]
    contact.service.user:
        class: ContactBundle\Service\UserService
        arguments: ["@logger", "@doctrine.orm.entity_manager", "@security.password_encoder", "%avatars_directory%", "%backgrounds_directory%"]
    acme_api.event.jwt_created_listener:
        class: ContactBundle\EventListener\JWTCreatedListener
        arguments: [ "@request_stack", "@doctrine.orm.entity_manager" ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
